apiVersion: v1
kind: Secret
metadata:
  name: gateway-token-reviewer-token
  namespace: akeyless
  annotations:
    kubernetes.io/service-account.name: gateway-token-reviewer
type: kubernetes.io/service-account-token
