apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo
  namespace: flask-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
        - name: flask-app
          image: docker.io/samgabrail/flask-todo:v0.0.13
          env:
            - name: DB_HOST
              value: mysql-flask-todo
            - name: DB_NAME
              value: todos
            - name: DYNAMIC_SECRET_TTL
              value: "3600"
            - name: FLASK_APP
              value: run.py
            - name: ENVIRONMENT
              value: remote
            - name: AKEYLESS_K8S_AUTH_ID
              value: p-tq5sw1ntenpykm
            - name: AKEYLESS_GATEWAY_URL
              value: https://opulent-zebra-97jg6jp9wvxh75v5-8000.app.github.dev
            - name: AKEYLESS_GATEWAY_API_URL
              value: https://opulent-zebra-97jg6jp9wvxh75v5-8081.app.github.dev
            - name: AKEYLESS_K8S_AUTH_CONFIG_NAME
              value: /Workshops/Workshop2/yousskadi/k8s-auth-method
            - name: DATABASE_DYNAMIC_SECRET_NAME
              value: /Workshops/Workshop2/yousskadi/mysql_password_dynamic
            - name: GITHUB_USERNAME
              value: yousskadi
          ports:
            - containerPort: 8080
